name: Build and deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Build and deploy
        env:
          GIT_AUTHOR_NAME: ${{ secrets.GIT_USER }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/Mina-1316/Mina-1316.github.io.git
          git config --global user.name "$GIT_AUTHOR_NAME"
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          yarn deploy -b deploy -u "$GIT_AUTHOR_EMAIL"
